name: Publish Python ğŸ distributions ğŸ“¦ to Test PyPI

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - "test-v*" # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build-n-publish:
    name: Build & publish Python ğŸ dist ğŸ“¦ to PyPI
    runs-on: ubuntu-18.04
    steps:
      - name: ğŸš› Checkout
        uses: actions/checkout@v2
      - name: ğŸš› Unshallow repo and fetch tags
        run: git fetch --prune --unshallow origin +refs/tags/*:refs/tags/*

      - name: ğŸ—ï¸ Set up Python 3.8
        uses: actions/setup-python@v1
        with: { python-version: 3.8 }

      - name: ğŸ˜·Run Tests
        run: python -m unittest discover -s tests

      - name: Black Code Formatter
        uses: lgeiger/black-action@master
        with:
          args: "--check --target-version py38 ."

      - name: ğŸ—ï¸ Install pep517
        run: python -m pip install pep517 --user

      - name: ğŸ Build a binary wheel and a source tarball
        run: python -m pep517.build --source --binary --out-dir dist/ .

      - name: Publish package ğŸ“¦ to TestPyPI
        if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@master
        with:
          user: __token__
          password: ${{ secrets.test_pypi_password }}
          repository_url: https://test.pypi.org/legacy/
